services:
  desweb_cq:
    restart: unless-stopped
    build: ./desweb_cq
    command: gunicorn desweb_cq.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./desweb_cq:/usr/src/app
    ports:
      - ${PRODUCTION_DOCKER_DJANGO_API_FORWARDED_PORT}:8000
    env_file:
      - .env
      - .env.prod
    networks:
      - postgis_postgis

networks:
   postgis_postgis:
      driver: bridge
      external: true
